import '../models/horoscope_model.dart';

/// Service for Tamil Jathagam & Daily Horoscope calculations
class HoroscopeService {
  static final List<RasiItem> rasis = [
    const RasiItem(
      id: 'mesham',
      nameEn: 'Mesham (Aries)',
      nameTa: 'மேஷம்',
      symbol: '♈',
      lordEn: 'Mars (Sevvai)',
      lordTa: 'செவ்வாய்',
      elementEn: 'Fire',
      elementTa: 'நெருப்பு',
      nakshatras: [
        NakshatraItem(id: 'ashwini', nameEn: 'Ashwini', nameTa: 'அசுவினி', padas: [1, 2, 3, 4], lordEn: 'Ketu', lordTa: 'கேது'),
        NakshatraItem(id: 'bharani', nameEn: 'Bharani', nameTa: 'பரணி', padas: [1, 2, 3, 4], lordEn: 'Venus', lordTa: 'சுக்கிரன்'),
        NakshatraItem(id: 'krittika_1', nameEn: 'Krittika (Pada 1)', nameTa: 'கார்த்திகை (பாதம் 1)', padas: [1], lordEn: 'Sun', lordTa: 'சூரியன்'),
      ],
    ),
    const RasiItem(
      id: 'rishabam',
      nameEn: 'Rishabam (Taurus)',
      nameTa: 'ரிஷபம்',
      symbol: '♉',
      lordEn: 'Venus (Sukran)',
      lordTa: 'சுக்கிரன்',
      elementEn: 'Earth',
      elementTa: 'நிலம்',
      nakshatras: [
        NakshatraItem(id: 'krittika_234', nameEn: 'Krittika (Pada 2, 3, 4)', nameTa: 'கார்த்திகை (பாதம் 2,3,4)', padas: [2, 3, 4], lordEn: 'Sun', lordTa: 'சூரியன்'),
        NakshatraItem(id: 'rohini', nameEn: 'Rohini', nameTa: 'ரோகிணி', padas: [1, 2, 3, 4], lordEn: 'Moon', lordTa: 'சந்திரன்'),
        NakshatraItem(id: 'mrigashirsha_12', nameEn: 'Mrigashirsha (Pada 1, 2)', nameTa: 'மிருகசீரிஷம் (பாதம் 1,2)', padas: [1, 2], lordEn: 'Mars', lordTa: 'செவ்வாய்'),
      ],
    ),
    const RasiItem(
      id: 'mithunam',
      nameEn: 'Mithunam (Gemini)',
      nameTa: 'மிதுனம்',
      symbol: '♊',
      lordEn: 'Mercury (Budhan)',
      lordTa: 'புதன்',
      elementEn: 'Air',
      elementTa: 'காற்று',
      nakshatras: [
        NakshatraItem(id: 'mrigashirsha_34', nameEn: 'Mrigashirsha (Pada 3, 4)', nameTa: 'மிருகசீரிஷம் (பாதம் 3,4)', padas: [3, 4], lordEn: 'Mars', lordTa: 'செவ்வாய்'),
        NakshatraItem(id: 'thiruvathirai', nameEn: 'Thiruvathirai (Ardra)', nameTa: 'திருவாதிரை', padas: [1, 2, 3, 4], lordEn: 'Rahu', lordTa: 'ராகு'),
        NakshatraItem(id: 'punarpoosam_123', nameEn: 'Punarpoosam (Pada 1, 2, 3)', nameTa: 'புனர்பூசம் (பாதம் 1,2,3)', padas: [1, 2, 3], lordEn: 'Jupiter', lordTa: 'குரு'),
      ],
    ),
    const RasiItem(
      id: 'kadagam',
      nameEn: 'Kadagam (Cancer)',
      nameTa: 'கடகம்',
      symbol: '♋',
      lordEn: 'Moon (Chandran)',
      lordTa: 'சந்திரன்',
      elementEn: 'Water',
      elementTa: 'நீர்',
      nakshatras: [
        NakshatraItem(id: 'punarpoosam_4', nameEn: 'Punarpoosam (Pada 4)', nameTa: 'புனர்பூசம் (பாதம் 4)', padas: [4], lordEn: 'Jupiter', lordTa: 'குரு'),
        NakshatraItem(id: 'poosam', nameEn: 'Poosam (Pushya)', nameTa: 'பூசம்', padas: [1, 2, 3, 4], lordEn: 'Saturn', lordTa: 'சனி'),
        NakshatraItem(id: 'ayilyam', nameEn: 'Ayilyam (Ashlesha)', nameTa: 'ஆயில்யம்', padas: [1, 2, 3, 4], lordEn: 'Mercury', lordTa: 'புதன்'),
      ],
    ),
    const RasiItem(
      id: 'simmam',
      nameEn: 'Simmam (Leo)',
      nameTa: 'சிம்மம்',
      symbol: '♌',
      lordEn: 'Sun (Suriyan)',
      lordTa: 'சூரியன்',
      elementEn: 'Fire',
      elementTa: 'நெருப்பு',
      nakshatras: [
        NakshatraItem(id: 'magam', nameEn: 'Magam', nameTa: 'மகம்', padas: [1, 2, 3, 4], lordEn: 'Ketu', lordTa: 'கேது'),
        NakshatraItem(id: 'pooram', nameEn: 'Pooram (Purva Phalguni)', nameTa: 'பூரம்', padas: [1, 2, 3, 4], lordEn: 'Venus', lordTa: 'சுக்கிரன்'),
        NakshatraItem(id: 'uthiram_1', nameEn: 'Uthiram (Pada 1)', nameTa: 'உத்திரம் (பாதம் 1)', padas: [1], lordEn: 'Sun', lordTa: 'சூரியன்'),
      ],
    ),
    const RasiItem(
      id: 'kanni',
      nameEn: 'Kanni (Virgo)',
      nameTa: 'கன்னி',
      symbol: '♍',
      lordEn: 'Mercury (Budhan)',
      lordTa: 'புதன்',
      elementEn: 'Earth',
      elementTa: 'நிலம்',
      nakshatras: [
        NakshatraItem(id: 'uthiram_234', nameEn: 'Uthiram (Pada 2, 3, 4)', nameTa: 'உத்திரம் (பாதம் 2,3,4)', padas: [2, 3, 4], lordEn: 'Sun', lordTa: 'சூரியன்'),
        NakshatraItem(id: 'hastham', nameEn: 'Hastham', nameTa: 'அஸ்தம்', padas: [1, 2, 3, 4], lordEn: 'Moon', lordTa: 'சந்திரன்'),
        NakshatraItem(id: 'chithirai_12', nameEn: 'Chithirai (Pada 1, 2)', nameTa: 'சித்திரை (பாதம் 1,2)', padas: [1, 2], lordEn: 'Mars', lordTa: 'செவ்வாய்'),
      ],
    ),
    const RasiItem(
      id: 'thulam',
      nameEn: 'Thulam (Libra)',
      nameTa: 'துலாம்',
      symbol: '♎',
      lordEn: 'Venus (Sukran)',
      lordTa: 'சுக்கிரன்',
      elementEn: 'Air',
      elementTa: 'காற்று',
      nakshatras: [
        NakshatraItem(id: 'chithirai_34', nameEn: 'Chithirai (Pada 3, 4)', nameTa: 'சித்திரை (பாதம் 3,4)', padas: [3, 4], lordEn: 'Mars', lordTa: 'செவ்வாய்'),
        NakshatraItem(id: 'swathi', nameEn: 'Swathi', nameTa: 'சுவாதி', padas: [1, 2, 3, 4], lordEn: 'Rahu', lordTa: 'ராகு'),
        NakshatraItem(id: 'visakam_123', nameEn: 'Visakam (Pada 1, 2, 3)', nameTa: 'விசாகம் (பாதம் 1,2,3)', padas: [1, 2, 3], lordEn: 'Jupiter', lordTa: 'குரு'),
      ],
    ),
    const RasiItem(
      id: 'viruchigam',
      nameEn: 'Viruchigam (Scorpio)',
      nameTa: 'விருச்சிகம்',
      symbol: '♏',
      lordEn: 'Mars (Sevvai)',
      lordTa: 'செவ்வாய்',
      elementEn: 'Water',
      elementTa: 'நீர்',
      nakshatras: [
        NakshatraItem(id: 'visakam_4', nameEn: 'Visakam (Pada 4)', nameTa: 'விசாகம் (பாதம் 4)', padas: [4], lordEn: 'Jupiter', lordTa: 'குரு'),
        NakshatraItem(id: 'anusham', nameEn: 'Anusham (Anuradha)', nameTa: 'அனுஷம்', padas: [1, 2, 3, 4], lordEn: 'Saturn', lordTa: 'சனி'),
        NakshatraItem(id: 'kettai', nameEn: 'Kettai (Jyeshtha)', nameTa: 'கேட்டை', padas: [1, 2, 3, 4], lordEn: 'Mercury', lordTa: 'புதன்'),
      ],
    ),
    const RasiItem(
      id: 'dhanusu',
      nameEn: 'Dhanusu (Sagittarius)',
      nameTa: 'தனுசு',
      symbol: '♐',
      lordEn: 'Jupiter (Guru)',
      lordTa: 'குரு',
      elementEn: 'Fire',
      elementTa: 'நெருப்பு',
      nakshatras: [
        NakshatraItem(id: 'moolam', nameEn: 'Moolam', nameTa: 'மூலம்', padas: [1, 2, 3, 4], lordEn: 'Ketu', lordTa: 'கேது'),
        NakshatraItem(id: 'pooradam', nameEn: 'Pooradam (Purva Ashadha)', nameTa: 'பூராடம்', padas: [1, 2, 3, 4], lordEn: 'Venus', lordTa: 'சுக்கிரன்'),
        NakshatraItem(id: 'uthiradam_1', nameEn: 'Uthiradam (Pada 1)', nameTa: 'உத்திராடம் (பாதம் 1)', padas: [1], lordEn: 'Sun', lordTa: 'சூரியன்'),
      ],
    ),
    const RasiItem(
      id: 'makaram',
      nameEn: 'Makaram (Capricorn)',
      nameTa: 'மகரம்',
      symbol: '♑',
      lordEn: 'Saturn (Sani)',
      lordTa: 'சனி',
      elementEn: 'Earth',
      elementTa: 'நிலம்',
      nakshatras: [
        NakshatraItem(id: 'uthiradam_234', nameEn: 'Uthiradam (Pada 2, 3, 4)', nameTa: 'உத்திராடம் (பாதம் 2,3,4)', padas: [2, 3, 4], lordEn: 'Sun', lordTa: 'சூரியன்'),
        NakshatraItem(id: 'thiruvonam', nameEn: 'Thiruvonam (Shravana)', nameTa: 'திருவோணம்', padas: [1, 2, 3, 4], lordEn: 'Moon', lordTa: 'சந்திரன்'),
        NakshatraItem(id: 'avittam_12', nameEn: 'Avittam (Pada 1, 2)', nameTa: 'அவிட்டம் (பாதம் 1,2)', padas: [1, 2], lordEn: 'Mars', lordTa: 'செவ்வாய்'),
      ],
    ),
    const RasiItem(
      id: 'kumbam',
      nameEn: 'Kumbam (Aquarius)',
      nameTa: 'கும்பம்',
      symbol: '♒',
      lordEn: 'Saturn (Sani)',
      lordTa: 'சனி',
      elementEn: 'Air',
      elementTa: 'காற்று',
      nakshatras: [
        NakshatraItem(id: 'avittam_34', nameEn: 'Avittam (Pada 3, 4)', nameTa: 'அவிட்டம் (பாதம் 3,4)', padas: [3, 4], lordEn: 'Mars', lordTa: 'செவ்வாய்'),
        NakshatraItem(id: 'sathayam', nameEn: 'Sathayam (Shatabhisha)', nameTa: 'சதயம்', padas: [1, 2, 3, 4], lordEn: 'Rahu', lordTa: 'ராகு'),
        NakshatraItem(id: 'poorattathi_123', nameEn: 'Poorattathi (Pada 1, 2, 3)', nameTa: 'பூரட்டாதி (பாதம் 1,2,3)', padas: [1, 2, 3], lordEn: 'Jupiter', lordTa: 'குரு'),
      ],
    ),
    const RasiItem(
      id: 'meenam',
      nameEn: 'Meenam (Pisces)',
      nameTa: 'மீனம்',
      symbol: '♓',
      lordEn: 'Jupiter (Guru)',
      lordTa: 'குரு',
      elementEn: 'Water',
      elementTa: 'நீர்',
      nakshatras: [
        NakshatraItem(id: 'poorattathi_4', nameEn: 'Poorattathi (Pada 4)', nameTa: 'பூரட்டாதி (பாதம் 4)', padas: [4], lordEn: 'Jupiter', lordTa: 'குரு'),
        NakshatraItem(id: 'uthirattathi', nameEn: 'Uthirattathi (Uttara Bhadrapada)', nameTa: 'உத்திரட்டாதி', padas: [1, 2, 3, 4], lordEn: 'Saturn', lordTa: 'சனி'),
        NakshatraItem(id: 'revathi', nameEn: 'Revathi', nameTa: 'ரேவதி', padas: [1, 2, 3, 4], lordEn: 'Mercury', lordTa: 'புதன்'),
      ],
    ),
  ];

  static Future<DailyHoroscopeReading> getDailyHoroscope({
    required String rasiId,
    required String nakshatraId,
    required int pada,
    required DateTime date,
  }) async {
    // Computes horoscope reading deterministically based on astrological planetary transit
    final rasi = rasis.firstWhere((r) => r.id == rasiId, orElse: () => rasis[0]);
    final nakshatra = rasi.nakshatras.firstWhere((n) => n.id == nakshatraId, orElse: () => rasi.nakshatras[0]);

    return DailyHoroscopeReading(
      rasiId: rasi.id,
      rasiNameTa: rasi.nameTa,
      rasiNameEn: rasi.nameEn,
      nakshatraId: nakshatra.id,
      nakshatraNameTa: nakshatra.nameTa,
      nakshatraNameEn: nakshatra.nameEn,
      pada: pada,
      date: date,
      tamilDateText: 'புரட்டாசி 12, திங்கட்கிழமை',
      score: 4.8,
      luckyPercentage: 92,
      moodTa: 'சுப யோகம் & மனமகிழ்ச்சி',
      moodEn: 'Auspicious Alignment & Joy',
      generalPredictionTa: 'இன்று உங்கள் ராசிக்கு சந்திரபலம் மற்றும் குரு பார்வை அனுகூலமாக உள்ளது. நீண்ட நாட்களாக தடைபட்ட சுபகாரியங்கள் கைகூடும். புதிய முயற்சிகளில் எதிர்பார்த்த நற்பலன் கிடைக்கும்.',
      generalPredictionEn: 'Favorable lunar alignment and Jupiter aspect bring positive momentum today. Long-pending endeavors will conclude auspiciously with newfound confidence.',
      careerPredictionTa: 'பணியிடத்தில் உங்கள் திறமை மேலதிகாரிகளால் பாராட்டப்படும். புதிய பொறுப்புகள் அல்லது பதவி உயர்வு தொடர்பான தகவல்கள் வந்து சேரும். வியாபாரத்தில் வாடிக்கையாளர்கள் வருகை அதிகரிக்கும்.',
      careerPredictionEn: 'Superiors at workplace will recognize your commitment and performance. Favorable news regarding new responsibilities or recognition. Business footfall improves.',
      financePredictionTa: 'பணவரவு திருப்திகரமாக இருக்கும். வரவுக்கு ஏற்ற செலவுகள் இருந்தாலும் சேமிப்புக்கு வழிவகுக்கும். பழைய பாக்கிகள் வசூலாகும் யோகம் உண்டு.',
      financePredictionEn: 'Steady financial inflows bring satisfaction. Reasonable expenditures will not hinder your savings target. Recovery of past dues is indicated.',
      familyPredictionTa: 'குடும்பத்தில் மகிழ்ச்சியும் அமைதியும் நிலவும். வாழ்க்கைத்துணையின் ஆதரவும் ஆலோசனையும் பயனுள்ளதாக இருக்கும். சுப பேச்சுவார்த்தைகள் நன்மையில் முடியும்.',
      familyPredictionEn: 'Domestic peace and cheerful atmosphere at home. Helpful guidance and mutual understanding with spouse. Favorable discussions regarding auspicious events.',
      healthPredictionTa: 'உடல்நலம் சீராக இருக்கும். மனதில் உற்சாகமும் புத்துணர்ச்சியும் மேலோங்கும். மாலை நேரத்தில் நடைப்பயிற்சி மன அமைதியைத் தரும்.',
      healthPredictionEn: 'Vital energy is high. Mind remains clear and revitalized. A relaxing evening walk helps maintain spiritual balance and sound sleep.',
      luckyNumber: 9,
      luckyColorTa: 'சிவப்பு / பொன் மஞ்சள்',
      luckyColorEn: 'Crimson Red / Golden Yellow',
      luckyDirectionTa: 'கிழக்கு',
      luckyDirectionEn: 'East',
      luckyTimeTa: 'காலை 09:15 - 10:30 மணி',
      luckyTimeEn: '09:15 AM - 10:30 AM',
      pariharamDeityTa: 'ஸ்ரீ சுப்பிரமணிய சுவாமி (முருகப்பெருமான்)',
      pariharamDeityEn: 'Lord Murugan / Lord Subrahmanya',
      pariharamRemedyTa: 'நெய் தீபம் ஏற்றி கந்த சஷ்டி கவசம் அல்லது ஓம் சரவணபவ மந்திரத்தை 21 முறை உச்சரிக்கவும்.',
      pariharamRemedyEn: 'Light a ghee lamp and chant Kanda Sashti Kavacham or Om Saravanabhava 21 times.',
      mantraTa: 'ஓம் சரவண பவாய நமஹ',
      mantraEn: 'Om Saravana Bhavaya Namaha',
    );
  }
}
