class PersonalEvent {
  final String id;
  final String userId;
  final String title;
  final String? description;
  final DateTime startTime;
  final DateTime endTime;
  final bool isAllDay;
  final String timezone;
  final String? location;
  final String category;
  final String? colorLabel;
  final bool isCompleted;
  final String? recurrenceRule;
  final String? linkUrl;

  PersonalEvent({
    required this.id,
    required this.userId,
    required this.title,
    this.description,
    required this.startTime,
    required this.endTime,
    required this.isAllDay,
    required this.timezone,
    this.location,
    required this.category,
    this.colorLabel,
    required this.isCompleted,
    this.recurrenceRule,
    this.linkUrl,
  });

  factory PersonalEvent.fromJson(Map<String, dynamic> json) {
    return PersonalEvent(
      id: json['id'] as String,
      userId: json['user_id'] as String,
      title: json['title'] as String,
      description: json['description'] as String?,
      startTime: DateTime.parse(json['start_time'] as String).toLocal(),
      endTime: DateTime.parse(json['end_time'] as String).toLocal(),
      isAllDay: json['is_all_day'] as bool? ?? false,
      timezone: json['timezone'] as String? ?? 'Asia/Kolkata',
      location: json['location'] as String?,
      category: json['category'] as String? ?? 'Personal',
      colorLabel: json['color_label'] as String?,
      isCompleted: json['is_completed'] as bool? ?? false,
      recurrenceRule: json['recurrence_rule'] as String?,
      linkUrl: json['link_url'] as String?,
    );
  }

  /// Used for UPDATE — includes id for the .eq() filter.
  /// user_id is intentionally excluded to prevent ownership re-assignment.
  Map<String, dynamic> toJsonForUpdate() {
    return {
      'title': title,
      'description': description,
      'start_time': startTime.toUtc().toIso8601String(),
      'end_time': endTime.toUtc().toIso8601String(),
      'is_all_day': isAllDay,
      'timezone': timezone,
      'location': location,
      'category': category,
      'color_label': colorLabel,
      'is_completed': isCompleted,
      'recurrence_rule': recurrenceRule,
      'link_url': linkUrl,
    };
  }

  /// Used for INSERT — omits id (generated by DB) and user_id (set by RLS policy context).
  /// The RLS INSERT policy enforces auth.uid() = user_id so we still send user_id
  /// to satisfy the NOT NULL constraint, but the DB will reject if it doesn't match.
  Map<String, dynamic> toJsonForInsert() {
    return {
      'user_id': userId,
      'title': title,
      'description': description,
      'start_time': startTime.toUtc().toIso8601String(),
      'end_time': endTime.toUtc().toIso8601String(),
      'is_all_day': isAllDay,
      'timezone': timezone,
      'location': location,
      'category': category,
      'color_label': colorLabel,
      'is_completed': isCompleted,
      'recurrence_rule': recurrenceRule,
      'link_url': linkUrl,
    };
  }
}
