import 'package:flutter/material.dart';
import 'package:url_launcher/url_launcher.dart';
import '../../../core/constants/colors.dart';
import '../../../core/localization/tnt_localizations.dart';
import '../config/catering_config.dart';
import '../models/catering_enquiry.dart';
import '../repositories/catering_repository.dart';
import 'package:intl/intl.dart';

class CateringEnquiryScreen extends StatefulWidget {
  final DateTime? initialDate;

  const CateringEnquiryScreen({super.key, this.initialDate});

  @override
  State<CateringEnquiryScreen> createState() => _CateringEnquiryScreenState();
}

class _CateringEnquiryScreenState extends State<CateringEnquiryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _cateringRepo = CateringRepository();

  bool _isSubmitting = false;
  bool _isSuccess = false;
  String? _referenceCode;

  final TextEditingController _nameController = TextEditingController();
  final TextEditingController _mobileController = TextEditingController();
  final TextEditingController _guestController = TextEditingController();
  final TextEditingController _locationController = TextEditingController();
  final TextEditingController _messageController = TextEditingController();

  String? _selectedEventType;
  DateTime? _selectedDate;

  @override
  void initState() {
    super.initState();
    _selectedDate = widget.initialDate;
  }

  @override
  void dispose() {
    _nameController.dispose();
    _mobileController.dispose();
    _guestController.dispose();
    _locationController.dispose();
    _messageController.dispose();
    super.dispose();
  }

  Future<void> _launchUrl(String url) async {
    final uri = Uri.parse(url);
    if (await canLaunchUrl(uri)) {
      await launchUrl(uri, mode: LaunchMode.externalApplication);
    }
  }

  void _openWhatsApp(String? reference, String? name, String? event, String? date, String? guests, String? location, String? msg) {
    String text;
    if (_isSuccess && reference != null) {
      text = "Hello Shree Taste & Taste Catering,\n\nI have submitted a catering enquiry through TNT Tamil Calendar.\n\nEnquiry Details:\nName: $name\nEvent: $event\nDate: $date\nGuests: $guests\nLocation: $location\n\nReference:\n$reference\n\nAdditional Details:\n$msg\n\nThank you.";
    } else {
      text = "Hello Shree Taste & Taste Catering,\n\nI found your catering service through TNT Tamil Calendar.\n\nI would like to know more about your catering services.\n\nThank you.";
    }
    
    final encodedText = Uri.encodeComponent(text);
    _launchUrl('https://wa.me/${CateringContactConfig.whatsappNumber}?text=$encodedText');
  }

  Future<void> _submitEnquiry() async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedEventType == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select an event type')));
      return;
    }
    if (_selectedDate == null) {
      ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Please select an event date')));
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final enquiry = CateringEnquiry(
        referenceCode: '', // Generated by repo
        fullName: _nameController.text.trim(),
        mobileNumber: _mobileController.text.trim().replaceAll(' ', ''),
        eventType: _selectedEventType!,
        eventDate: _selectedDate!,
        guestCount: int.tryParse(_guestController.text.trim()),
        eventLocation: _locationController.text.trim(),
        message: _messageController.text.trim(),
        createdAt: DateTime.now(),
        updatedAt: DateTime.now(),
      );

      final result = await _cateringRepo.submitEnquiry(enquiry);

      setState(() {
        _isSuccess = true;
        _referenceCode = result.referenceCode;
        _isSubmitting = false;
      });
    } catch (e) {
      setState(() => _isSubmitting = false);
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('Unable to send your enquiry right now. Please try again.')),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final localizations = TNTLocalizationsProvider.of(context)?.localizations;
    final isTamil = localizations?.language == AppLanguage.tamil;
    String translate(String key) => localizations?.translate(key) ?? key;

    return Scaffold(
      appBar: AppBar(
        title: const Text(
          CateringContactConfig.businessName,
          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16),
        ),
        backgroundColor: TNTColors.surface,
        elevation: 0,
      ),
      backgroundColor: TNTColors.background,
      body: _isSuccess ? _buildSuccessView() : _buildEnquiryForm(translate, isTamil),
    );
  }

  Widget _buildSuccessView() {
    return Center(
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Icon(Icons.check_circle_outline, size: 80, color: Colors.green),
            const SizedBox(height: 24),
            const Text(
              'Enquiry Sent Successfully',
              style: TextStyle(fontSize: 20, fontWeight: FontWeight.bold, color: TNTColors.textPrimary),
            ),
            const SizedBox(height: 12),
            const Text(
              'Thank you for contacting\nShree Taste & Taste Catering.\n\nOur team will contact you regarding your event.',
              textAlign: TextAlign.center,
              style: TextStyle(fontSize: 14, color: TNTColors.textSecondary, height: 1.5),
            ),
            const SizedBox(height: 24),
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 8),
              decoration: BoxDecoration(
                color: TNTColors.primary.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Text(
                'Reference: $_referenceCode',
                style: const TextStyle(fontSize: 14, fontWeight: FontWeight.bold, color: TNTColors.primary),
              ),
            ),
            const SizedBox(height: 32),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                ElevatedButton.icon(
                  onPressed: () => _launchUrl('tel:${CateringContactConfig.phoneNumber}'),
                  icon: const Icon(Icons.call, size: 18),
                  label: const Text('Call'),
                  style: ElevatedButton.styleFrom(backgroundColor: TNTColors.surface, foregroundColor: TNTColors.primary),
                ),
                const SizedBox(width: 16),
                ElevatedButton.icon(
                  onPressed: () => _openWhatsApp(
                    _referenceCode,
                    _nameController.text,
                    _selectedEventType,
                    _selectedDate != null ? DateFormat('dd MMM yyyy').format(_selectedDate!) : '',
                    _guestController.text,
                    _locationController.text,
                    _messageController.text,
                  ),
                  icon: const Icon(Icons.chat, size: 18),
                  label: const Text('WhatsApp'),
                  style: ElevatedButton.styleFrom(backgroundColor: const Color(0xFF25D366), foregroundColor: Colors.white),
                ),
              ],
            ),
            const SizedBox(height: 24),
            TextButton(
              onPressed: () => Navigator.pop(context),
              child: const Text('Done', style: TextStyle(fontWeight: FontWeight.bold)),
            )
          ],
        ),
      ),
    );
  }

  Widget _buildEnquiryForm(String Function(String) translate, bool isTamil) {
    return Form(
      key: _formKey,
      child: ListView(
        padding: const EdgeInsets.symmetric(horizontal: 16, vertical: 16),
        children: [
          // Hero Image Fallback
          ClipRRect(
            borderRadius: BorderRadius.circular(12),
            child: Image.network(
              CateringContactConfig.referenceImageUrl,
              height: 180,
              width: double.infinity,
              fit: BoxFit.cover,
              errorBuilder: (context, error, stackTrace) => Container(
                height: 120,
                color: TNTColors.primary.withValues(alpha: 0.1),
                alignment: Alignment.center,
                child: const Column(
                  mainAxisAlignment: MainAxisAlignment.center,
                  children: [
                    Text('🍽️', style: TextStyle(fontSize: 40)),
                    SizedBox(height: 8),
                    Text(CateringContactConfig.businessName, style: TextStyle(fontWeight: FontWeight.bold, color: TNTColors.primary)),
                  ],
                ),
              ),
            ),
          ),
          const SizedBox(height: 16),
          
          const Text(
            'Make your special occasions memorable with catering services from Shree Taste & Taste Catering.',
            style: TextStyle(fontSize: 14, color: TNTColors.textSecondary),
            textAlign: TextAlign.center,
          ),
          const SizedBox(height: 24),
          
          // Contact Us Card
          _buildContactCard(),
          const SizedBox(height: 24),

          // Events we cater for
          _buildEventsListCard(),
          const SizedBox(height: 32),

          const Divider(color: TNTColors.border),
          const SizedBox(height: 24),
          
          const Text(
            'Plan Your Event',
            style: TextStyle(fontSize: 18, fontWeight: FontWeight.bold, color: TNTColors.textPrimary),
          ),
          const SizedBox(height: 4),
          const Text(
            'Tell us about your event and our catering team can contact you.',
            style: TextStyle(fontSize: 13, color: TNTColors.textSecondary),
          ),
          const SizedBox(height: 24),

          // Event Type Selection
          const Text('What type of event are you planning? *', style: TextStyle(fontSize: 13, fontWeight: FontWeight.bold)),
          const SizedBox(height: 8),
          Wrap(
            spacing: 8,
            runSpacing: 8,
            children: CateringContactConfig.eventTypes.map((type) {
              final isSelected = _selectedEventType == type;
              return ChoiceChip(
                label: Text(type),
                selected: isSelected,
                onSelected: (selected) {
                  setState(() => _selectedEventType = selected ? type : null);
                },
                selectedColor: TNTColors.primary.withValues(alpha: 0.2),
                labelStyle: TextStyle(
                  color: isSelected ? TNTColors.primary : TNTColors.textPrimary,
                  fontWeight: isSelected ? FontWeight.bold : FontWeight.normal,
                  fontSize: 12,
                ),
                backgroundColor: TNTColors.surface,
                side: BorderSide(color: isSelected ? TNTColors.primary : TNTColors.border),
              );
            }).toList(),
          ),
          const SizedBox(height: 16),

          TextFormField(
            controller: _nameController,
            decoration: const InputDecoration(labelText: 'Full Name *', hintText: 'Enter your full name', border: OutlineInputBorder()),
            validator: (value) => value == null || value.trim().isEmpty ? 'Required' : null,
          ),
          const SizedBox(height: 16),
          
          TextFormField(
            controller: _mobileController,
            decoration: const InputDecoration(labelText: 'Mobile Number *', hintText: 'Enter your mobile number', border: OutlineInputBorder()),
            keyboardType: TextInputType.phone,
            validator: (value) => value == null || value.trim().isEmpty ? 'Required' : null,
          ),
          const SizedBox(height: 16),

          InkWell(
            onTap: () async {
              final date = await showDatePicker(
                context: context,
                initialDate: _selectedDate ?? DateTime.now(),
                firstDate: DateTime.now(),
                lastDate: DateTime.now().add(const Duration(days: 3650)),
              );
              if (date != null) {
                setState(() => _selectedDate = date);
              }
            },
            child: InputDecorator(
              decoration: const InputDecoration(labelText: 'Event Date *', border: OutlineInputBorder()),
              child: Text(_selectedDate != null ? DateFormat('dd MMM yyyy').format(_selectedDate!) : 'Select Date'),
            ),
          ),
          const SizedBox(height: 16),

          TextFormField(
            controller: _guestController,
            decoration: const InputDecoration(labelText: 'Number of Guests', hintText: 'e.g. 200', border: OutlineInputBorder()),
            keyboardType: TextInputType.number,
          ),
          const SizedBox(height: 16),

          TextFormField(
            controller: _locationController,
            decoration: const InputDecoration(labelText: 'Event Location', hintText: 'Enter event location / area', border: OutlineInputBorder()),
          ),
          const SizedBox(height: 16),

          TextFormField(
            controller: _messageController,
            decoration: const InputDecoration(labelText: 'Additional Message', hintText: 'Tell us anything else about your event...', border: OutlineInputBorder()),
            maxLines: 3,
          ),
          const SizedBox(height: 32),
          
          SizedBox(
            width: double.infinity,
            height: 48,
            child: ElevatedButton(
              onPressed: _isSubmitting ? null : _submitEnquiry,
              style: ElevatedButton.styleFrom(backgroundColor: TNTColors.primary, foregroundColor: Colors.white),
              child: _isSubmitting
                  ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(color: Colors.white, strokeWidth: 2))
                  : const Text('Send Enquiry', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
            ),
          ),
          const SizedBox(height: 40),
        ],
      ),
    );
  }

  Widget _buildContactCard() {
    return Container(
      padding: const EdgeInsets.all(16),
      decoration: BoxDecoration(
        color: TNTColors.surface,
        borderRadius: BorderRadius.circular(12),
        border: Border.all(color: TNTColors.border),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Text('Contact Us', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: TNTColors.textPrimary)),
          const SizedBox(height: 16),
          Row(
            children: [
              const Icon(Icons.phone, size: 16, color: TNTColors.textSecondary),
              const SizedBox(width: 8),
              Text(CateringContactConfig.displayPhoneNumber, style: const TextStyle(fontSize: 14, color: TNTColors.textPrimary)),
            ],
          ),
          const SizedBox(height: 8),
          Row(
            children: [
              const Icon(Icons.email, size: 16, color: TNTColors.textSecondary),
              const SizedBox(width: 8),
              Text(CateringContactConfig.email, style: const TextStyle(fontSize: 14, color: TNTColors.textPrimary)),
            ],
          ),
          const SizedBox(height: 16),
          Row(
            children: [
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: () => _launchUrl('tel:${CateringContactConfig.phoneNumber}'),
                  icon: const Icon(Icons.call, size: 14),
                  label: const Text('Call'),
                ),
              ),
              const SizedBox(width: 8),
              Expanded(
                child: OutlinedButton.icon(
                  onPressed: () => _openWhatsApp(null, null, null, null, null, null, null),
                  icon: const Icon(Icons.chat, size: 14),
                  label: const Text('WhatsApp'),
                ),
              ),
            ],
          ),
          const SizedBox(height: 8),
          SizedBox(
            width: double.infinity,
            child: OutlinedButton.icon(
              onPressed: () => _launchUrl('mailto:${CateringContactConfig.email}'),
              icon: const Icon(Icons.email, size: 14),
              label: const Text('Email Us'),
            ),
          ),
          const SizedBox(height: 24),
          const Text('📍 Our Location', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 14, color: TNTColors.textPrimary)),
          const SizedBox(height: 8),
          const Text(
            CateringContactConfig.address,
            style: TextStyle(fontSize: 13, color: TNTColors.textSecondary, height: 1.5),
          ),
          const SizedBox(height: 8),
          TextButton.icon(
            onPressed: () {
              final query = Uri.encodeComponent(CateringContactConfig.address.replaceAll('\n', ' '));
              _launchUrl('https://www.google.com/maps/search/?api=1&query=$query');
            },
            icon: const Icon(Icons.map, size: 14),
            label: const Text('Open in Maps'),
          ),
          const SizedBox(height: 16),
          SizedBox(
            width: double.infinity,
            child: TextButton.icon(
              onPressed: () => _launchUrl(CateringContactConfig.websiteUrl),
              icon: const Icon(Icons.language, size: 14),
              label: const Text('Visit Website'),
              style: TextButton.styleFrom(backgroundColor: TNTColors.primary.withValues(alpha: 0.05)),
            ),
          )
        ],
      ),
    );
  }

  Widget _buildEventsListCard() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text('Events We Cater For', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16, color: TNTColors.textPrimary)),
        const SizedBox(height: 12),
        Container(
          padding: const EdgeInsets.all(16),
          decoration: BoxDecoration(
            color: TNTColors.surface,
            borderRadius: BorderRadius.circular(12),
            border: Border.all(color: TNTColors.border),
          ),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: CateringContactConfig.eventTypes.map((type) {
              return Padding(
                padding: const EdgeInsets.only(bottom: 8.0),
                child: Row(
                  children: [
                    const Icon(Icons.arrow_right_alt, size: 16, color: TNTColors.primary),
                    const SizedBox(width: 8),
                    Text(type, style: const TextStyle(fontSize: 14, color: TNTColors.textSecondary)),
                  ],
                ),
              );
            }).toList(),
          ),
        ),
      ],
    );
  }
}
