// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE0pGpKGESss-wuD0KJnjAXbNrrZ5QO2k',
    appId: '1:592150777479:web:f1d02c1fcba41ce9ac3222',
    messagingSenderId: '592150777479',
    projectId: 'tnt-tamil-calendar',
    authDomain: 'tnt-tamil-calendar.firebaseapp.com',
    storageBucket: 'tnt-tamil-calendar.firebasestorage.app',
    measurementId: 'G-664HPCDBDT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNwEkVlN5r_m5Rfp1sssYZ_4ttIMheP_4',
    appId: '1:592150777479:android:e5cbc88db3d2cd1aac3222',
    messagingSenderId: '592150777479',
    projectId: 'tnt-tamil-calendar',
    storageBucket: 'tnt-tamil-calendar.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE0pGpKGESss-wuD0KJnjAXbNrrZ5QO2k',
    appId: '1:592150777479:web:7ffa8ed0cc02b3c8ac3222',
    messagingSenderId: '592150777479',
    projectId: 'tnt-tamil-calendar',
    authDomain: 'tnt-tamil-calendar.firebaseapp.com',
    storageBucket: 'tnt-tamil-calendar.firebasestorage.app',
    measurementId: 'G-EEJC0NTPJS',
  );
}
