import 'package:flutter/material.dart';

enum AppLanguage { tamil, english }

class TNTLocalizations {
  final AppLanguage language;

  TNTLocalizations(this.language);

  static final Map<AppLanguage, Map<String, String>> _localizedValues = {
    AppLanguage.tamil: {
      'app_name': 'TNT',
      'home': 'முகப்பு',
      'calendar': 'நாள்காட்டி',
      'panchangam': 'பஞ்சாங்கம்',
      'muhurtham': 'முகூர்த்தம்',
      'more': 'மேலும்',
      'today_tamil_date': 'இன்றைய தமிழ் தேதி',
      'today_panchangam': 'இன்றைய பஞ்சாங்கம்',
      'important_timings': 'முக்கிய நேரங்கள்',
      'nalla_neram': 'நல்ல நேரம்',
      'rahu_kalam': 'இராகு காலம்',
      'yamagandam': 'எமகண்டம்',
      'kuligai': 'குளிகை',
      'gowri_panchangam': 'கௌரி பஞ்சாங்கம்',
      'subha_horai': 'சுப ஹோரை',
      'sunrise': 'சூரியோதயம்',
      'sunset': 'சூரிய அஸ்தமனம்',
      'moonrise': 'சந்திரோதயம்',
      'moonset': 'சந்திர அஸ்தமனம்',
      'tithi': 'திதி',
      'nakshatra': 'நட்சத்திரம்',
      'yoga': 'யோகம்',
      'karana': 'கரணம்',
      'auspicious_day': 'சுப நாள்',
      'inauspicious_day': 'கரி நாள்',
      'marriage_muhurtham': 'திருமண முகூர்த்த நாட்கள்',
      'special_days': 'சிறப்பு நாட்கள்',
      'festivals': 'பண்டிகைகள்',
      'saved': 'சேமிக்கப்பட்டவை',
      'notifications': 'அறிவிப்புகள்',
      'settings': 'அமைப்புகள்',
      'about_tnt': 'TNT பற்றி',
      'profile': 'சுயவிவரம்',
      'location': 'இருப்பிடம்',
      'chennai': 'சென்னை',
      'madurai': 'மதுரை',
      'coimbatore': 'கோயம்புத்தூர்',
      'trichy': 'திருச்சி',
      'salem': 'சேலம்',
      'tirunelveli': 'திருநெல்வேலி',
      'language_selection': 'மொழி / Language',
      'change_language': 'மொழியை மாற்றவும்',
      'save_btn': 'சேமி',
      'reminder_btn': 'நினைவூட்டல்',
      'share_btn': 'பகிர்',
      'retry_btn': 'மீண்டும் முயற்சி செய்',
      'no_data': 'தகவல்கள் ஏதுமில்லை',
      'error_loading': 'தகவலை ஏற்றுவதில் பிழை ஏற்பட்டது. மீண்டும் முயற்சிக்கவும்.',
      'loading_tnt': 'TNT Tamil Calendar ஏற்றப்படுகிறது...',
      'connection_error': 'இணைய இணைப்பைச் சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'loading': 'ஏற்றப்படுகிறது...',
      'valarpirai': 'வளர்பிறை',
      'theipirai': 'தேய்பிறை',
      'welcome_back': 'நல்வரவு',
      
      // Auth Screen translations
      'email': 'மின்னஞ்சல்',
      'password': 'கடவுச்சொல்',
      'confirm_password': 'கடவுச்சொல்லை உறுதிப்படுத்தவும்',
      'full_name': 'முழு பெயர்',
      'mobile_number': 'கைபேசி எண்',
      'sign_in': 'உள்நுழைக',
      'sign_up': 'பதிவு செய்க',
      'forgot_password': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
      'forgot_password_desc': 'உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும். கடவுச்சொல்லை மீட்டமைப்பதற்கான இணைப்பை உங்களுக்கு அனுப்புவோம்.',
      'send_recovery_email': 'மீட்பு இணைப்பை அனுப்பு',
      'back_to_login': 'மீண்டும் உள்நுழைவு பக்கத்திற்கு செல்லவும்',
      'create_account': 'புதிய கணக்கை உருவாக்கவும்',
      'already_have_account': 'ஏற்கனவே கணக்கு உள்ளதா? உள்நுழைக',
      'passwords_dont_match': 'கடவுச்சொற்கள் பொருந்தவில்லை',
      'invalid_email': 'மின்னஞ்சல் முகவரி தவறானது',
      'field_cannot_be_empty': 'இந்த புலம் காலியாக இருக்கக்கூடாது',
      'password_too_short': 'கடவுச்சொல் குறைந்தது 6 எழுத்துக்களைக் கொண்டிருக்க வேண்டும்',
      'success_msg': 'வெற்றி',
      'recovery_email_sent_success': 'கடவுச்சொல் மீட்பு மின்னஞ்சல் வெற்றிகரமாக அனுப்பப்பட்டது.',
      'saving_profile': 'சுயவிவரத்தை சேமிக்கிறது...',
      'signing_in': 'உள்நுழைகிறது...',
      'signing_up': 'பதிவு செய்கிறது...',
      'signing_out': 'வெளியேறுகிறது...',
      'edit_profile': 'சுயவிவரத்தை திருத்தவும்',
      'city': 'நகரம்',
      'state': 'மாநிலம்',
      'country': 'நாடு',
      'notification_settings': 'அறிவிப்பு அமைப்புகள்',
      'enable_general_notif': 'அனைத்து அறிவிப்புகளையும் இயக்கு',
      'panchangam_notif': 'பஞ்சாங்கம் அறிவிப்புகள்',
      'festival_notif': 'பண்டிகை அறிவிப்புகள்',
      'muhurtham_notif': 'முகூர்த்த அறிவிப்புகள்',
      'special_day_notif': 'சிறப்பு நாள் அறிவிப்புகள்',
      'reminder_notif': 'நினைவூட்டல் அறிவிப்புகள்',
      'important_updates': 'முக்கிய பயன்பாட்டு புதுப்பிப்புகள்',
      'marketing_notif': 'சலுகைகள் மற்றும் விளம்பரங்கள்',
      'mark_all_read': 'அனைத்தும் படித்தவை',
      'notification_history': 'அறிவிப்பு வரலாறு',
      'logout': 'வெளியேறு',
      'logout_confirm': 'நீங்கள் நிச்சயமாக கணக்கிலிருந்து வெளியேற வேண்டுமா?',
      'cancel': 'ரத்து',
      'admin_dashboard': 'நிர்வாகி டாஷ்போர்டு',
      'admin_role_tag': 'நிர்வாகி',
      'user_role_tag': 'பயனர்',
      'total_users': 'மொத்த பயனர்கள்',
      'active_users': 'செயலில் உள்ள பயனர்கள்',
      'new_users': 'புதிய பயனர்கள்',
      'unauthorized_access': 'அனுமதி மறுக்கப்பட்டது. நீங்கள் ஒரு நிர்வாகி இல்லை.',
      'today': 'இன்று',
      'previous_day': 'முந்தைய நாள்',
      'next_day': 'அடுத்த நாள்',
      'refresh': 'புதுப்பி',
      'paksha': 'பட்சம்',
      'day_duration': 'பகல் பொழுது',
      'night_duration': 'இரவுப் பொழுது',
      'auspicious_time': 'சுப நேரம்',
      'inauspicious_time': 'அசுப நேரம்',
      'todays_special': 'இன்றைய சிறப்பு',
      'muhurtham_available': 'சுப முகூர்த்தம் உள்ளது',
      'no_muhurtham': 'இன்று சுப முகூர்த்தம் இல்லை',
      'view_muhurtham_details': 'முகூர்த்த விவரங்கள்',
      'data_unavailable': 'தகவல் கிடைக்கவில்லை',
      'select_date': 'தேதியைத் தேர்ந்தெடுக்கவும்',
      'select_location': 'இருப்பிடத்தைத் தேர்ந்தெடுக்கவும்',
      'use_current_location': 'தற்போதைய இருப்பிடத்தைப் பயன்படுத்து',
      'manual_city': 'நகரத்தைத் தேர்ந்தெடுக்கவும்',
      'save_panchangam': 'பஞ்சாங்கம் சேமிக்கப்பட்டது',
      'reminder_set': 'நினைவூட்டல் அமைக்கப்பட்டது',
      'share_panchangam': 'பஞ்சாங்கம் பகிரப்பட்டது',
      'panchangam_overview': 'பஞ்சாங்கக் குறிப்புகள்',
      'sun_moon_timings': 'சூரிய / சந்திர நேரங்கள்',
      'daily_timings': 'முக்கிய தினசரி நேரங்கள்',
      'all_categories': 'அனைத்து பிரிவுகள்',
      'marriage': 'திருமணம்',
      'engagement': 'நிச்சயதார்த்தம்',
      'housewarming': 'கிரகப்பிரவேசம்',
      'naming_ceremony': 'பெயர் சூட்டுதல்',
      'ear_piercing': 'காதணி விழா',
      'business_opening': 'தொழில் தொடங்குதல்',
      'vehicle_purchase': 'வாகனம் வாங்குதல்',
      'filter_by_phase': 'பட்சம் வடிகட்டி',
      'all_phases': 'அனைத்து பட்சம்',
      'muhurtham_dates': 'சுப முகூர்த்த நாட்கள்',
      'approved_muhurtham': 'அங்கீகரிக்கப்பட்ட சுப முகூர்த்தம்',
      'available_timings': 'கிடைக்கும் முகூர்த்த நேரங்கள்',
      'timings_count': 'முகூர்த்த நேரங்கள்',
      'muhurtham_details': 'முகூர்த்த விவரங்கள்',
      'muhurtham_timing': 'சுப முகூர்த்த நேரம்',
      'star_nakshatra': 'நட்சத்திரம்',
      'suitable_for': 'உகந்த காரியம்',
      'muhurtham_notes': 'முக்கிய வழிகாட்டுதல்கள்',
      'inauspicious_windows': 'தவிர்க்க வேண்டிய நேரங்கள்',
      'view_date_panchangam': 'இன்றைய முழு பஞ்சாங்கம் காண்க',
      'save_muhurtham': 'முகூர்த்தம் சேமிக்கப்பட்டது',
      'remove_muhurtham': 'முகூர்த்தம் நீக்கப்பட்டது',
      'reminder_dialog_title': 'நினைவூட்டல் அமைக்கவும்',
      'reminder_1_day_before': '1 நாளுக்கு முன் (மாலை 8:00)',
      'reminder_morning': 'நிகழ்வு அன்று காலை 6:00 மணிக்கு',
      'reminder_1_hour_before': 'முகூர்த்தத்திற்கு 1 மணி நேரம் முன்',
      'set_reminder_btn': 'நினைவூட்டலை உறுதி செய்',
      'share_muhurtham_title': 'சுப முகூர்த்த பகிர்வு',
      'copied_to_clipboard': 'விவரங்கள் நகலெடுக்கப்பட்டது',
      'no_muhurtham_found': 'தேர்ந்தெடுக்கப்பட்ட மாதத்தில் முகூர்த்த நாட்கள் இல்லை',
      'no_muhurtham_filter_desc': 'வடிகட்டிகளை மாற்றி மீண்டும் முயற்சிக்கவும்',
      'lagnam': 'லக்னம்',
      'duration': 'கால அளவு',
      'calendar_utilities': 'நாட்காட்டி பயன்பாடுகள்',
      'amavasai': 'அமாவாசை',
      'pournami': 'பௌர்ணமி',
      'pradosham': 'பிரதோஷம்',
      'sashti': 'சஷ்டி',
      'ekadashi': 'ஏகாதசி',
      'krithigai': 'கிருத்திகை',
      'chaturthi': 'சதுர்த்தி',
      'sankatahara_chaturthi': 'சங்கடஹர சதுர்த்தி',
      'ashtami': 'அஷ்டமி',
      'navami': 'நவமி',
      'government_holiday': 'அரசு விடுமுறை',
      'religious_festival': 'ஆன்மீகத் திருவிழா',
      'upcoming_festivals': 'வரவிருக்கும் பண்டிகைகள்',
      'upcoming_special_days': 'வரவிருக்கும் சிறப்பு நாட்கள்',
      'todays_festival': 'இன்றைய பண்டிகை',
      'todays_special_day': 'இன்றைய சிறப்பு நாள்',
      'view_all': 'அனைத்தையும் காண்க',
      'festival_details': 'திருவிழா விவரங்கள்',
      'special_day_details': 'சிறப்பு நாள் விவரங்கள்',
      'deity': 'வழிபடும் தெய்வம்',
      'rituals': 'பூஜை முறைகள் & விரத நியதிகள்',
      'significance': 'ஆன்மீக முக்கியத்துவம்',
      'no_festivals_found': 'தேர்ந்தெடுக்கப்பட்ட மாதத்தில் பண்டிகைகள் இல்லை',
      'no_special_days_found': 'தேர்ந்தெடுக்கப்பட்ட மாதத்தில் சிறப்பு நாட்கள் இல்லை',
      'save_festival': 'பண்டிகை சேமிக்கப்பட்டது',
      'remove_festival': 'பண்டிகை நீக்கப்பட்டது',
      'save_special_day': 'சிறப்பு நாள் சேமிக்கப்பட்டது',
      'remove_special_day': 'சிறப்பு நாள் நீக்கப்பட்டது',
      'share_festival_title': 'சுப திருவிழா பகிர்வு',
      'share_special_day_title': 'சிறப்பு நாள் தகவல் பகிர்வு',
      'published_badge': 'அங்கீகரிக்கப்பட்டது',
      'all_festivals': 'அனைத்துப் பண்டிகைகள்',
      'hindu_festivals': 'இந்துப் பண்டிகைகள்',
      'christian_festivals': 'கிறிஸ்தவப் பண்டிகைகள்',
      'muslim_festivals': 'இஸ்லாமியப் பண்டிகைகள்',
      'government_holidays': 'அரசு விடுமுறைகள்',
      'observance_timing': 'விரத நேரம் / காலம்',
    },
    AppLanguage.english: {
      'app_name': 'TNT',
      'home': 'Home',
      'calendar': 'Calendar',
      'panchangam': 'Panchangam',
      'muhurtham': 'Muhurtham',
      'more': 'More',
      'today_tamil_date': "Today's Tamil Date",
      'today_panchangam': "Today's Panchangam",
      'important_timings': 'Important Timings',
      'nalla_neram': 'Nalla Neram',
      'rahu_kalam': 'Rahu Kalam',
      'yamagandam': 'Yamagandam',
      'kuligai': 'Kuligai',
      'gowri_panchangam': 'Gowri Panchangam',
      'subha_horai': 'Subha Horai',
      'sunrise': 'Sunrise',
      'sunset': 'Sunset',
      'moonrise': 'Moonrise',
      'moonset': 'Moonset',
      'tithi': 'Tithi',
      'nakshatra': 'Nakshatra',
      'yoga': 'Yoga',
      'karana': 'Karana',
      'auspicious_day': 'Auspicious Day',
      'inauspicious_day': 'Inauspicious Day',
      'marriage_muhurtham': 'Marriage Muhurtham',
      'special_days': 'Special Days',
      'festivals': 'Festivals',
      'saved': 'Saved',
      'notifications': 'Notifications',
      'settings': 'Settings',
      'about_tnt': 'About TNT',
      'profile': 'Profile',
      'location': 'Location',
      'chennai': 'Chennai',
      'madurai': 'Madurai',
      'coimbatore': 'Coimbatore',
      'trichy': 'Trichy',
      'salem': 'Salem',
      'tirunelveli': 'Tirunelveli',
      'language_selection': 'Language / மொழி',
      'change_language': 'Change Language',
      'save_btn': 'Save',
      'reminder_btn': 'Reminder',
      'share_btn': 'Share',
      'retry_btn': 'Retry',
      'no_data': 'No Data Available',
      'error_loading': 'Failed to load details. Please try again.',
      'loading_tnt': 'Loading TNT Tamil Calendar...',
      'connection_error': 'Please check your internet connection and try again.',
      'loading': 'Loading...',
      'valarpirai': 'Valarpirai',
      'theipirai': 'Theipirai',
      'welcome_back': 'Welcome Back',

      // Auth Screen translations
      'email': 'Email',
      'password': 'Password',
      'confirm_password': 'Confirm Password',
      'full_name': 'Full Name',
      'mobile_number': 'Mobile Number',
      'sign_in': 'Sign In',
      'sign_up': 'Sign Up',
      'forgot_password': 'Forgot Password?',
      'forgot_password_desc': 'Enter your registered email address below. We will send you a password recovery link.',
      'send_recovery_email': 'Send Recovery Link',
      'back_to_login': 'Back to Login',
      'create_account': 'Create New Account',
      'already_have_account': 'Already have an account? Sign In',
      'passwords_dont_match': 'Passwords do not match',
      'invalid_email': 'Invalid email address',
      'field_cannot_be_empty': 'This field cannot be empty',
      'password_too_short': 'Password must be at least 6 characters',
      'success_msg': 'Success',
      'recovery_email_sent_success': 'Password recovery email sent successfully.',
      'saving_profile': 'Saving profile...',
      'signing_in': 'Signing in...',
      'signing_up': 'Signing up...',
      'signing_out': 'Signing out...',
      'edit_profile': 'Edit Profile',
      'city': 'City',
      'state': 'State',
      'country': 'Country',
      'notification_settings': 'Notification Preferences',
      'enable_general_notif': 'Enable All Notifications',
      'panchangam_notif': 'Panchangam Notifications',
      'festival_notif': 'Festival Announcements',
      'muhurtham_notif': 'Muhurtham Dates Alerts',
      'special_day_notif': 'Special Days Alerts',
      'reminder_notif': 'Reminder Alerts',
      'important_updates': 'Important App Updates',
      'marketing_notif': 'Promotions and Offers',
      'mark_all_read': 'Mark all as read',
      'notification_history': 'Notification History',
      'logout': 'Log Out',
      'logout_confirm': 'Are you sure you want to log out?',
      'cancel': 'Cancel',
      'admin_dashboard': 'Admin Dashboard',
      'admin_role_tag': 'Admin',
      'user_role_tag': 'User',
      'total_users': 'Total Users',
      'active_users': 'Active Users',
      'new_users': 'New Users',
      'unauthorized_access': 'Access Denied. You are not an administrator.',
      'today': 'Today',
      'previous_day': 'Previous Day',
      'next_day': 'Next Day',
      'refresh': 'Refresh',
      'paksha': 'Paksha',
      'day_duration': 'Day Duration',
      'night_duration': 'Night Duration',
      'auspicious_time': 'Auspicious Time',
      'inauspicious_time': 'Inauspicious Time',
      'todays_special': "Today's Special",
      'muhurtham_available': 'Muhurtham Available',
      'no_muhurtham': 'No Muhurtham Today',
      'view_muhurtham_details': 'View Muhurtham Details',
      'data_unavailable': 'Data unavailable',
      'select_date': 'Select Date',
      'select_location': 'Select Location',
      'use_current_location': 'Use Current Location',
      'manual_city': 'Select City Manually',
      'save_panchangam': 'Panchangam Saved',
      'reminder_set': 'Reminder Set',
      'share_panchangam': 'Panchangam Shared',
      'panchangam_overview': 'Panchangam Overview',
      'sun_moon_timings': 'Sun & Moon Timings',
      'daily_timings': 'Daily Important Timings',
      'all_categories': 'All Categories',
      'marriage': 'Marriage',
      'engagement': 'Engagement',
      'housewarming': 'Housewarming',
      'naming_ceremony': 'Naming Ceremony',
      'ear_piercing': 'Ear Piercing',
      'business_opening': 'Business Opening',
      'vehicle_purchase': 'Vehicle Purchase',
      'filter_by_phase': 'Phase Filter',
      'all_phases': 'All Phases',
      'muhurtham_dates': 'Auspicious Muhurtham Dates',
      'approved_muhurtham': 'Approved Auspicious Muhurtham',
      'available_timings': 'Available Muhurtham Timings',
      'timings_count': 'Muhurtham Timings',
      'muhurtham_details': 'Muhurtham Details',
      'muhurtham_timing': 'Muhurtham Timing',
      'star_nakshatra': 'Nakshatra',
      'suitable_for': 'Suitable For',
      'muhurtham_notes': 'Important Astrological Notes',
      'inauspicious_windows': 'Inauspicious Windows to Avoid',
      'view_date_panchangam': "View Day's Full Panchangam",
      'save_muhurtham': 'Muhurtham Saved to Bookmarks',
      'remove_muhurtham': 'Muhurtham Removed from Bookmarks',
      'reminder_dialog_title': 'Set Muhurtham Reminder',
      'reminder_1_day_before': '1 Day Before (8:00 PM)',
      'reminder_morning': 'Day of Event at 6:00 AM',
      'reminder_1_hour_before': '1 Hour Before Muhurtham',
      'set_reminder_btn': 'Confirm Reminder',
      'share_muhurtham_title': 'Share Auspicious Muhurtham',
      'copied_to_clipboard': 'Muhurtham details copied to clipboard',
      'no_muhurtham_found': 'No approved Muhurtham dates for this month',
      'no_muhurtham_filter_desc': 'Try selecting a different filter or month',
      'lagnam': 'Lagnam',
      'duration': 'Duration',
      'calendar_utilities': 'Calendar Utilities',
      'amavasai': 'Amavasai (New Moon)',
      'pournami': 'Pournami (Full Moon)',
      'pradosham': 'Pradosham',
      'sashti': 'Sashti',
      'ekadashi': 'Ekadashi',
      'krithigai': 'Krithigai',
      'chaturthi': 'Chaturthi',
      'sankatahara_chaturthi': 'Sankatahara Chaturthi',
      'ashtami': 'Ashtami',
      'navami': 'Navami',
      'government_holiday': 'Government Holiday',
      'religious_festival': 'Religious Festival',
      'upcoming_festivals': 'Upcoming Festivals',
      'upcoming_special_days': 'Upcoming Special Days',
      'todays_festival': "Today's Festival",
      'todays_special_day': "Today's Special Day",
      'view_all': 'View All',
      'festival_details': 'Festival Details',
      'special_day_details': 'Special Day Details',
      'deity': 'Associated Deity',
      'rituals': 'Rituals & Vrat Rules',
      'significance': 'Spiritual Significance',
      'no_festivals_found': 'No festivals found for this month',
      'no_special_days_found': 'No special days found for this selection',
      'save_festival': 'Festival Saved',
      'remove_festival': 'Festival Removed from Saved',
      'save_special_day': 'Special Day Saved',
      'remove_special_day': 'Special Day Removed from Saved',
      'share_festival_title': 'Share Festival',
      'share_special_day_title': 'Share Special Day',
      'published_badge': 'Verified & Published',
      'all_festivals': 'All Festivals',
      'hindu_festivals': 'Hindu Festivals',
      'christian_festivals': 'Christian Festivals',
      'muslim_festivals': 'Islamic Festivals',
      'government_holidays': 'Government Holidays',
      'observance_timing': 'Observance Window / Time',
    }
  };

  String translate(String key) {
    return _localizedValues[language]?[key] ?? key;
  }
}

// InheritedWidget to provide TNTLocalizations downward through the tree easily
class TNTLocalizationsProvider extends InheritedWidget {
  final TNTLocalizations localizations;
  final Function(AppLanguage) onLanguageChanged;

  const TNTLocalizationsProvider({
    super.key,
    required this.localizations,
    required this.onLanguageChanged,
    required super.child,
  });

  static TNTLocalizationsProvider? of(BuildContext context) {
    return context.dependOnInheritedWidgetOfExactType<TNTLocalizationsProvider>();
  }

  @override
  bool updateShouldNotify(TNTLocalizationsProvider oldWidget) {
    return oldWidget.localizations.language != localizations.language;
  }
}
